##########################################
## ATBC Advanced stats course
## Robert Bagchi
## 13-19/7/2014
##########################################


## Prac 8: Generalised least squares


rm(list=ls())
library(nlme)
library(ggplot2)
getwd()
setwd("/Users/kyletomlinson/Dropbox/Teaching/XTBG advanced stats 2022/Lectures/Lesson 8 GLS exercises")


####################################################
## Exercise 8.1
####################################################


plants <- read.csv('exampledata/plantdamage.csv')
summary(plants)

plants$shadehouse <- as.factor(plants$shadehouse)
plants$light <- as.factor(plants$light)


## can combine with random effects with lme
mod1 <- lme(growth~damage*light, random=~1|shadehouse,data=plants)
plot(mod1)  # looks exponential


## look at the residuals in the different light treatments
plot(mod1, resid(.)~fitted(.)|light, abline=0, layout=c(2, 1))
plot(mod1, resid(.)~fitted(.)|damage+light, abline=0, layout=c(3, 2))
## more variation in the light treatment

##add weights into the model
mod1b <- lme(growth~damage*light, random=~1|shadehouse, 
             data=plants,weights=varIdent(form=~1|light))

anova(mod1, mod1b) ## model fit is much better with weights

#look at residual plots
plot(mod1)
quartz()
plot(mod1b)   # much better homogeneity


plot(mod1b, (abs(resid(., type='p')))^(1/2)~fitted(.)|light,type=c('smooth', 'p'))



#now check the outputs
summary(mod1)
summary(mod1b)   
#in this case coefficients are stronger, but there is no obvious reason that this should be the case


#we could also model assuming that the variance is exponential
mod1c <- lme(growth~damage*light, random=~1|shadehouse,data=plants,weights=varExp(form=~fitted(.)))
anova(mod1, mod1c)
summary(mod1c)
plot(mod1c)  # residuals are homogeneous

plot(mod1c, sqrt(abs(resid(.)))~fitted(.), abline=0, layout=c(2, 1))


#of course using the gls in this way is a fix
# it turns out that if we consider growth to be exponential from the start, then the variance differences between the greenhouse light treatments fade away ..

mod2 <- lme(log(growth+3)~damage*light, random=~1|shadehouse, data=plants)
plot(mod2)  #heterogeneity has disappeared

plot(mod2, resid(.)~fitted(.)|light, abline=0, layout=c(2, 1))
#no difference in variance between light treatments anymore

mod2b <- lme(log(growth+3)~damage*light, random=~1|shadehouse, data=plants,weights=varIdent(form=~1|light))

anova(mod2,mod2b)   ## no significant improvement

#now compare mod5b and mod6
summary(mod1c)
summary(mod2)


#please note that the residuals generated by both methods look good, but the conclusions reached are VERY different: in mod 1c the interaction term is significant, but in mod 2 the interaction term is NOT significant 

#moral of the story: gls can be used to fix structural error, but its always better to understand what might be causing the structural error instead! 
#in this case, its the fact that plants inherently grow exponentially that is critical information for setting up the better model (Linear modelling assumption #1: the model should be naturally meaningful)




########################################################
# Exercise 8.2: spatial correlation
#########################################################


trees <- read.csv('exampledata/trees.csv')
dim(trees)
summary(trees)
trees$sp <- as.factor(trees$sp)
head(trees)

ggplot(data=trees, aes(x=x, y=y, colour=li, size=RGR)) +
  geom_point() + facet_wrap(~sp) + coord_equal()

#reduce our data to one species
#trees <- subset(trees,sp=="Pa")


## naive model
m.tree1 <- lm(RGR ~ li*sp, data=trees)
anova(m.tree1)
summary(m.tree1)

## naive model again using gls function
m.tree2 <- gls(RGR ~ li*sp, data=trees)
coef(m.tree1)
coef(m.tree2) ## same result; gls assumes identity matrix

plot(trees$li*sp,m.tree2$resid)  ## residuals dont look too bad

## but if we plot them spatially, there appears to be pattern
quartz()
ggplot(data=trees, aes(x=x, y=y, colour=li, size=m.tree2$resid)) +
  geom_point() + facet_wrap(~sp) + coord_equal()
    


## our variogram definitely indicates spatial correlation
quartz()
plot(Variogram(m.tree2, form=~x+y,resType='n')) ## definitely some spatial effects
#it also looks like there is a large nugget, but first we will model the autocorrelation without a nugget


## trying a gls model - takes a while
m.tree3 <- gls(RGR~li*sp, correlation=corExp(form=~x+y),data=trees)

anova(m.tree2, m.tree3) ## autocorrelation model fits better

#compare the two outputs; you will see the autocorrelation model has an extra parameter
coef(summary(m.tree2))
coef(summary(m.tree3))

#now replot the variogram to see whether the fitted model has dealt with the autocorrelation

plot(Variogram(m.tree3, form=~x+y, resType='n')) ## still some trend

m.tree4 <- update(m.tree3, correlation=corSpher(form=~x+y))
plot(Variogram(m.tree4, form=~x+y, resType='n')) ## still has trend and worse than corExp


#now add a nugget
m.tree3a <- gls(RGR~li*sp, correlation=corExp(form=~x+y, nugget=T),data=trees)
summary(m.tree3a)
plot(Variogram(m.tree3a, form=~x+y, resType='n'))  #trend removed!



AIC(m.tree2, m.tree3, m.tree4,m.tree3a)
## model with exponential effect and nugget the best.

#look at summary
summary(m.tree3a)



